//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusCommunication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin
    {
        public int id { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        public string name { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "This feild is required")]
        public string email { get; set; }
        [StringLength(10, MinimumLength = 3)]
        [Required(ErrorMessage = "This feild is required")]
        [DataType(DataType.Password)]
        public string password { get; set; }
    }
}
