//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusCommunication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class planbb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public planbb()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public int landline_plans_id { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        public string name { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        public int price { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        public string validity { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        public string local_plan { get; set; }
        
        public string std_plan { get; set; }

        public string messaging_for_mobiles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        public virtual planb planb { get; set; }
    }
}
