//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusCommunication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public int product_id { get; set; }
        public int price { get; set; }
        public int quantity { get; set; }
        public int total { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
